package pl.polsl.tab.fleetmanagement.report;


import com.itextpdf.text.*;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.Date;


public class Report {

    private static String FILE = "FirstPdf.pdf";
    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
            Font.BOLD);
    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.NORMAL, BaseColor.RED);
    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
            Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);
    private static BaseFont helvetica;

    static {
        try {
            helvetica = BaseFont.createFont(BaseFont.TIMES_ROMAN, BaseFont.CP1250, BaseFont.EMBEDDED);
        } catch (DocumentException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private static final Font helvetica16 =new Font(helvetica,12);

    public Report(HttpServletResponse response) {
        try {
            Document document = new Document();
            PdfWriter.getInstance(document, response.getOutputStream());
            document.open();
            addMetaData(document);
            addTitlePage(document);
            addContent(document);
            document.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // iText allows to add metadata to the PDF which can be viewed in your Adobe
    // Reader
    // under File -> Properties
    private static void addMetaData(Document document) {
        document.addTitle("My first PDF");
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("Lars Vogel");
        document.addCreator("Lars Vogel");
    }

    private static void addTitlePage(Document document)
            throws DocumentException {
        Paragraph preface = new Paragraph();
        // We add one empty line
        addEmptyLine(preface, 1);
        // Lets write a big header
        preface.add(new Paragraph("Koszty serwisowe i eksploatacyjce", catFont));

        addEmptyLine(preface, 1);
        // Will create: Report generated by: _name, _date
        preface.add(new Paragraph(
                "Report generated by: " + System.getProperty("user.name") + ", " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
                smallBold));
        addEmptyLine(preface, 3);
        preface.add(new Paragraph(
                "Testowanko ", smallBold));

        addEmptyLine(preface, 8);

        preface.add(new Paragraph(
                "UWAGA UWAGA UWAGA UWAGA UWAGA UWAGA UWAGA UWAGA UWAGA UWAGA",
                redFont));

        document.add(preface);
        // Start a new page
        document.newPage();
    }

    private static void addContent(Document document) throws DocumentException {
        Anchor anchor = new Anchor("First Chapter", catFont);
        anchor.setName("First Chapter");

        // Second parameter is the number of the chapter
        Chapter catPart = new Chapter(new Paragraph(anchor), 1);

        Paragraph subPara = new Paragraph("Subcategory 1", subFont);
        Section subCatPart = catPart.addSection(subPara);
        subCatPart.add(new Paragraph("Gram sety gorące jak Diplo cały kraj się jara moją ksywką\n" +
                "Cały kraj jara się moją bibką kiedy za stołem miksuję ten hip hop\n" +
                "Miksuję ten hip hop wszystko co zrobiłam to było dopiero intro\n" +
                "Z dancehallem miksuję ten hip hop bomboclaat\n" +
                "Skaczesz na parkiecie a zrobiło się już widno\n" +
                "Kiedyś to codziennie miałam klub teraz mam tu pełny stół\n" +
                "Z ziomalami dzielę się na pół każdy ruch to wspólny move\n" +
                "Chcę dostać ordery królowej imprezy a potem królowej afterów\n" +
                "Bo mi się należy (tak jest)\n" +
                "Wie każdy kto ze mną coś przeżył\n" +
                "Noce nie bywają spokojne będzie trzeba to pójdę na wojnę\n" +
                "Na ulicy w szeleszczącej kurtce Moncler będę walczyć o zwrot moich wspomnień\n" +
                "Bo chcecie nam zabrać ten czas i te radosne bankiety\n" +
                "Oddajcie lokale i hajs nie cenzurujcie poety\n" +
                "Czekam aż znowu będziemy popijać Bacardi w klubie ze szklanki\n" +
                "Gdy na parkiecie nasze fanki a na głośniku Nicki i Cardi\n" +
                "Nie mów nikomu łamiemy zasady bo w domu też bywa funky\n" +
                "Kiedy wpadają koleżanki zaczynają się hulanki\n" +
                "Czekam aż znowu będziemy popijać Bacardi w klubie ze szklanki\n" +
                "Gdy na parkiecie nasze fanki a na głośniku Nicki i Cardi\n" +
                "Nie mów nikomu łamiemy zasady bo w domu też bywa funky\n" +
                "Kiedy wpadają koleżanki zaczynają się hulanki\n" +
                "Wbijaj do mnie na house party z nami bawią się sąsiadki\n" +
                "Najpierw kozackie wieczory potem w radiu Bolesne Poranki\n" +
                "Mój typ melanżu to takie tańczone rąk pełna sala przez noc i przez dobę\n" +
                "Buja się cały klub z nogi na nogę chcę już wieczory spędzać poza domem\n" +
                "Zawsze stać za DJ ką tam gdzie z nieba sypie się bankroll\n" +
                "Tam gdzie laski tańczą na pewno błyszczą sukienką\n" +
                "Chodzą z torebką gdzie chłopakom chodzi tylko o jedno\n" +
                "W moim mieście chodzi tylko o jedno\n" +
                "Czekam aż znowu będziemy popijać Bacardi w klubie ze szklanki\n" +
                "Gdy na parkiecie nasze fanki a na głośniku Nicki i Cardi\n" +
                "Nie mów nikomu łamiemy zasady bo w domu też bywa funky\n" +
                "Kiedy wpadają koleżanki zaczynają się hulanki\n" +
                "Czekam aż znowu będziemy popijać Bacardi w klubie ze szklanki\n" +
                "Gdy na parkiecie nasze fanki a na głośniku Nicki i Cardi\n" +
                "Nie mów nikomu łamiemy zasady bo w domu też bywa funky\n" +
                "Kiedy wpadają koleżanki zaczynają się hulanki", helvetica16));

        subPara = new Paragraph("Subcategory 2", subFont);
        subCatPart = catPart.addSection(subPara);
        subCatPart.add(new Paragraph("Paragraph 1"));
        subCatPart.add(new Paragraph("Paragraph 2"));
        subCatPart.add(new Paragraph("Paragraph 3"));

        // add a list
        createList(subCatPart);
        Paragraph paragraph = new Paragraph();
        addEmptyLine(paragraph, 5);
        subCatPart.add(paragraph);

        // add a table
        createTable(subCatPart);

        // now add all this to the document
        document.add(catPart);

        // Next section
        anchor = new Anchor("Second Chapter", catFont);
        anchor.setName("Second Chapter");

        // Second parameter is the number of the chapter
        catPart = new Chapter(new Paragraph(anchor), 1);

        subPara = new Paragraph("Subcategory", subFont);
        subCatPart = catPart.addSection(subPara);
        subCatPart.add(new Paragraph("This is a very important message"));

        // now add all this to the document
        document.add(catPart);

    }

    private static void createTable(Section subCatPart)
            throws BadElementException {
        PdfPTable table = new PdfPTable(3);

        // t.setBorderColor(BaseColor.GRAY);
        // t.setPadding(4);
        // t.setSpacing(4);
        // t.setBorderWidth(1);

        PdfPCell c1 = new PdfPCell(new Phrase("Table Header 1"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Table Header 2"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Table Header 3"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        table.setHeaderRows(1);

        table.addCell("1.0");
        table.addCell("1.1");
        table.addCell("1.2");
        table.addCell("2.1");
        table.addCell("2.2");
        table.addCell("2.3");

        subCatPart.add(table);

    }

    private static void createList(Section subCatPart) {
        List list = new List(true, false, 10);
        list.add(new ListItem("First point"));
        list.add(new ListItem("Second point"));
        list.add(new ListItem("Third point"));
        subCatPart.add(list);
    }

    private static void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }
}
